[package]
name = "ipvs-tcp-from-scratch-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { workspace = true, optional = true }
strum_macros = "0.26.4"

[lib]
path = "src/lib.rs"
